fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
    apt : "https://github.com/puppetlabs/puppetlabs-apt.git"

# profile module layout, default include ntp module
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
    telegraf: "https://github.com/datacentred/puppet-telegraf.git"

  symlinks:
    profile_influxdb: "#{source_dir}"
